%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# Left Camera calibration and distortion parameters (OpenCV)
Camera1.fx: 389.8786751831381
Camera1.fy: 390.0057935555469
Camera1.cx: 320.26379272664826
Camera1.cy: 238.4832794310755

# distortion parameters
Camera1.k1: 0.004065789357143795
Camera1.k2: -0.006608954224092335
Camera1.p1: -0.0002526561570573827
Camera1.p2: 0.0016732286267698915
Camera1.k3: 0.0

# Right Camera calibration and distortion parameters (OpenCV)
Camera2.fx: 389.68553511340957
Camera2.fy: 389.8386062915859
Camera2.cx: 319.9989897969349
Camera2.cy: 238.43165398148108

# distortion parameters
Camera2.k1: 0.00628500368524081
Camera2.k2: -0.008253985129956022
Camera2.p1: -0.00007301703008467886
Camera2.p2: 0.0006871823227224392
Camera2.k3: 0.0

# Camera resolution
Camera.width: 640
Camera.height: 480

# Camera frames per second
Camera.fps: 15

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
Stereo.ThDepth: 40.0
Stereo.b: 0.09508051770963907

Stereo.T_c1_c2: !!opencv-matrix
  rows: 4
  cols: 4
  dt: f
  data: [ 0.99999791, 0.00005676, 0.00204162, -0.09508,
          -0.00005716, 0.99999998, 0.00019404, -0.00012117,
          -0.00204161, -0.00019415, 0.9999979, -0.000291,
          0.0, 0.0, 0.0, 1.0 ]

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------
# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1250

# ORB Extractor: Scale factor between levels in the scale pyramid
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 6.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -3.5
Viewer.ViewpointF: 500.0
