%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# Left Camera calibration and distortion parameters (OpenCV)
Camera1.fx: 524.5311783830005
Camera1.fy: 524.0312654561258
Camera1.cx: 645.729359376349
Camera1.cy: 364.81196392209125

# distortion parameters
Camera1.k1: -0.030941453530945084
Camera1.k2: -0.004690060553035204
Camera1.p1: 0.001371851108543066
Camera1.p2: 0.00010924151874123159
Camera1.k3: 0.0

# Right Camera calibration and distortion parameters (OpenCV)
Camera2.fx: 525.9667239113255
Camera2.fy: 525.3034447527817
Camera2.cx: 639.1570788662424
Camera2.cy: 362.5480936910761

# distortion parameters
Camera2.k1: -0.029498474347103426
Camera2.k2: -0.0054223673783414285
Camera2.p1: 0.000711158722239985
Camera2.p2: 0.000193035488714221
Camera2.k3: 0.0

# Camera resolution
Camera.width: 1280
Camera.height: 720

# Camera frames per second
Camera.fps: 15

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
Stereo.ThDepth: 40.0
Stereo.b: 0.12017451981719099

Stereo.T_c1_c2: !!opencv-matrix
  rows: 4
  cols: 4
  dt: f
  data: [ 0.99999534, -0.00190358, -0.00238647, -0.12017373,
          0.0019002, 0.99999719, -0.00141641, -0.00003835,
          0.00238916, 0.00141187, 0.99999615, -0.0004345,
          0.0, 0.0, 0.0, 1.0 ]

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------
# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1250

# ORB Extractor: Scale factor between levels in the scale pyramid
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 6.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -3.5
Viewer.ViewpointF: 500.0
